<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="13" passed="8" failed="5" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-03-14T10:49:52 CET" name="Default suite" finished-at="2021-03-14T10:49:59 CET" duration-ms="7539">
    <groups>
    </groups>
    <test started-at="2021-03-14T10:49:52 CET" name="Default test" finished-at="2021-03-14T10:49:59 CET" duration-ms="7539">
      <class name="com.userPosts.tests.UserBlogPostTest">
        <test-method is-config="true" signature="init()[pri:0, instance:com.userPosts.tests.UserBlogPostTest@2cd2a21f]" started-at="2021-03-14T10:49:52 CET" name="init" finished-at="2021-03-14T10:49:53 CET" duration-ms="1050" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="createNewComment()[pri:0, instance:com.userPosts.tests.UserBlogPostTest@2cd2a21f]" started-at="2021-03-14T10:49:53 CET" name="createNewComment" finished-at="2021-03-14T10:49:55 CET" duration-ms="2092" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [201] but found [201]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [201] but found [201]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at com.userPosts.tests.UserBlogPostTest.createNewComment(UserBlogPostTest.java:77)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewComment -->
        <test-method signature="createNewCommentWithInvalidEmailAddress()[pri:0, instance:com.userPosts.tests.UserBlogPostTest@2cd2a21f]" started-at="2021-03-14T10:49:55 CET" name="createNewCommentWithInvalidEmailAddress" finished-at="2021-03-14T10:49:55 CET" duration-ms="422" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [201] but found [201]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [201] but found [201]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at com.userPosts.tests.UserBlogPostTest.createNewCommentWithInvalidEmailAddress(UserBlogPostTest.java:101)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewCommentWithInvalidEmailAddress -->
        <test-method signature="createNewCommentWithInvalidPostId()[pri:0, instance:com.userPosts.tests.UserBlogPostTest@2cd2a21f]" started-at="2021-03-14T10:49:55 CET" name="createNewCommentWithInvalidPostId" finished-at="2021-03-14T10:49:55 CET" duration-ms="295" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [404] but found [201]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [404] but found [201]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at com.userPosts.tests.UserBlogPostTest.createNewCommentWithInvalidPostId(UserBlogPostTest.java:123)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewCommentWithInvalidPostId -->
        <test-method signature="createNewPost()[pri:0, instance:com.userPosts.tests.UserBlogPostTest@2cd2a21f]" started-at="2021-03-14T10:49:55 CET" name="createNewPost" finished-at="2021-03-14T10:49:56 CET" duration-ms="401" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [201] but found [201]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [201] but found [201]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at com.userPosts.tests.UserBlogPostTest.createNewPost(UserBlogPostTest.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewPost -->
        <test-method signature="createNewPostWithInvalidUserId()[pri:0, instance:com.userPosts.tests.UserBlogPostTest@2cd2a21f]" started-at="2021-03-14T10:49:56 CET" name="createNewPostWithInvalidUserId" finished-at="2021-03-14T10:49:56 CET" duration-ms="465" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [404] but found [201]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [404] but found [201]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at com.userPosts.tests.UserBlogPostTest.createNewPostWithInvalidUserId(UserBlogPostTest.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewPostWithInvalidUserId -->
      </class> <!-- com.userPosts.tests.UserBlogPostTest -->
      <class name="com.userPosts.tests.UserBlogGetTest">
        <test-method is-config="true" signature="init()[pri:0, instance:com.userPosts.tests.UserBlogGetTest@2e55dd0c]" started-at="2021-03-14T10:49:56 CET" name="init" finished-at="2021-03-14T10:49:56 CET" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="GetAllCommentsForAllPosts()[pri:0, instance:com.userPosts.tests.UserBlogGetTest@2e55dd0c]" started-at="2021-03-14T10:49:56 CET" name="GetAllCommentsForAllPosts" finished-at="2021-03-14T10:49:57 CET" duration-ms="244" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetAllCommentsForAllPosts -->
        <test-method signature="GetAllPosts()[pri:0, instance:com.userPosts.tests.UserBlogGetTest@2e55dd0c]" started-at="2021-03-14T10:49:57 CET" name="GetAllPosts" finished-at="2021-03-14T10:49:57 CET" duration-ms="186" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetAllPosts -->
        <test-method signature="GetAllPostsFromSpecificUser()[pri:0, instance:com.userPosts.tests.UserBlogGetTest@2e55dd0c]" started-at="2021-03-14T10:49:57 CET" name="GetAllPostsFromSpecificUser" finished-at="2021-03-14T10:49:57 CET" duration-ms="184" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetAllPostsFromSpecificUser -->
        <test-method signature="GetPostwhichDoesNotExist()[pri:0, instance:com.userPosts.tests.UserBlogGetTest@2e55dd0c]" started-at="2021-03-14T10:49:57 CET" name="GetPostwhichDoesNotExist" finished-at="2021-03-14T10:49:57 CET" duration-ms="168" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetPostwhichDoesNotExist -->
        <test-method signature="GetTheCommentsForOnePost()[pri:0, instance:com.userPosts.tests.UserBlogGetTest@2e55dd0c]" started-at="2021-03-14T10:49:57 CET" name="GetTheCommentsForOnePost" finished-at="2021-03-14T10:49:57 CET" duration-ms="163" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetTheCommentsForOnePost -->
        <test-method signature="GetUsername()[pri:0, instance:com.userPosts.tests.UserBlogGetTest@2e55dd0c]" started-at="2021-03-14T10:49:57 CET" name="GetUsername" finished-at="2021-03-14T10:49:58 CET" duration-ms="1215" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetUsername -->
        <test-method signature="PostMessageBody()[pri:0, instance:com.userPosts.tests.UserBlogGetTest@2e55dd0c]" started-at="2021-03-14T10:49:59 CET" name="PostMessageBody" finished-at="2021-03-14T10:49:59 CET" duration-ms="224" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PostMessageBody -->
        <test-method signature="ValidateEmailFormat()[pri:0, instance:com.userPosts.tests.UserBlogGetTest@2e55dd0c]" started-at="2021-03-14T10:49:59 CET" name="ValidateEmailFormat" finished-at="2021-03-14T10:49:59 CET" duration-ms="352" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateEmailFormat -->
      </class> <!-- com.userPosts.tests.UserBlogGetTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
